### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by szepeviktor** [inpsyde/reusable-workflows#6]
### Description of the bug

- Please consider switching to Yarn in your organization. And Benefit!
- `inpsyde/workflows` would be a straight-forward package name :)
- `contains(github.ref, 'refs/tags/')` is really `github.ref_type` 💡 
- Please do not use downstream scripts: `composer compile-assets`
- `npm install` is an update command, issue [`npm ci`](https://docs.npmjs.com/cli/v8/commands/npm-ci)
- the tool `cs2pr` is unused
- `./node_modules/.bin/stylelint` is really `npx stylelint`
- `./vendor/bin/phpunit` is really `composer exec phpunit`
- when you develop a package/library try adding a CI job that installs that package into a sample application

All the best to you! ❤️ 

### Reproduction instructions

-

### Expected behavior

-

### Environment info

-

### Relevant log output

```shell
-
```

### Additional context

-

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tyrann0us** [comment]
Hi @szepeviktor,

Thank you for taking the time to create this issue.
Please note that I will close it again as any details to explain your points are missing.

Please create separate issues for each point and especially make sure to select the appropriate issue type and actually fill out the issue form. Because without context, we cannot guarantee that we will consider your suggestions.

Thanks,
Philipp

**Comment by szepeviktor** [comment]
> any details to explain your points are missing.

It is simple: your CI is good enough but not perfect.

I leave all the above issues uo to you.
